/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.UUID;
public class App {
    public void run() {
        UUID uuidV7=UuidUtil.generateV7();
        java.util.List<Integer> nums = java.util.List.of(1, 2, 3, 4);

        int sum = kotlin.collections.CollectionsKt.sumOfInt(nums);
        var s ="{fooo}";
        var s2=kotlin.text.StringsKt.removeSurrounding(s, "{", "}");

        System.out.println("s2: " + s2);
        System.out.println("uuidV7: " + uuidV7);
        System.out.println("sum: " + sum);
    }

    public static void main(String[] args) {
        new App().run();
    }
}
