/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import kotlin.collections.CollectionsKt;
import kotlin.text.StringsKt;

import java.util.List;
import java.util.UUID;

record FooRecord(int id, String name, String countryCode) {
}

public class App {
    public void run() {
        UUID uuidV7 = UuidUtil.generateV7();
        System.out.println("uuidV7: " + uuidV7);

        List<Integer> nums = List.of(1, 2, 3, 4);
        int sum = CollectionsKt.sumOfInt(nums);
        System.out.println("sum: " + sum);

        var javaList = List.of(1, 2, 3, 4);
        var kotlinList = CollectionsKt.toList(javaList);
        var x1 = ListChain.of(kotlinList)
                .dropLast(2)
                .reversed();
        System.out.println("x1: " + x1);

        var s = "{fooo}";
        var s2 = StringsKt.removeSurrounding(s, "{", "}");
        System.out.println("s2: " + s2);

        var result =
                Chain.of("foo, bar, baz, qux")
                        .map(String::trim)
                        .map(String::toUpperCase)
                        //.filter(kotlin.text.StringsKt::isBlank)
                        .filter(it -> it.length() > 3)
                        .filter((it) -> !StringsKt.isBlank(it))
                        .get();

        System.out.println("result: " + result);

        var records = List.of(
                new FooRecord(1, "a", "DE"),
                new FooRecord(2, "b", "DE"),
                new FooRecord(1, "c", "US"),
                new FooRecord(3, "d", "GB")
        );
        var recordsTransformed = ListChain.of(records)
                .sortedBy(org.example.FooRecord::id)
                .distinctBy(it -> it.id())
                .map(it -> new FooRecord(it.id(), it.name(), it.countryCode()))
                .groupBy(x -> x.countryCode());

        System.out.println("recordsTransformed: " + recordsTransformed);

        var recordsTransformed2 = ListChain.of(records)
                .map(it -> it.name())
                .joinToString(", ", "[", "]", null, null);
        System.out.println("recordsTransformed2: " + recordsTransformed2);
    }

    public static void main(String[] args) {
        new App().run();
    }
}
